completion  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:265)
estimation  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:267)
trends  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:270)
_.format_commands  # Click override called via duck-typing (packages/taskdog-ui/src/taskdog/cli_main.py:138)
_.show_audit_logs  # unused method (packages/taskdog-ui/src/taskdog/tui/app.py:478)
SelectionProvider  # unused import (packages/taskdog-ui/src/taskdog/tui/context.py:12)
SelectionProvider  # unused class (packages/taskdog-ui/src/taskdog/tui/selection.py:9)
last_update  # unused variable (packages/taskdog-ui/src/taskdog/tui/state/connection_status.py:19)
tasks_cache  # unused variable (packages/taskdog-ui/src/taskdog/tui/state/tui_state.py:57)
_.tasks_cache  # unused attribute (packages/taskdog-ui/src/taskdog/tui/state/tui_state.py:253)
_.get_legend_text  # unused method (packages/taskdog-ui/src/taskdog/tui/widgets/gantt_data_table.py:640)
_.matches  # unused method (packages/taskdog-ui/src/taskdog/tui/widgets/task_search_filter.py:67)
VI_ALL_BINDINGS  # unused variable (packages/taskdog-ui/src/taskdog/tui/widgets/vi_navigation_mixin.py:96)
VI_SCROLL_BINDINGS  # unused variable (packages/taskdog-ui/src/taskdog/tui/widgets/vi_navigation_mixin.py:105)
VI_SCROLL_ALL_BINDINGS  # unused variable (packages/taskdog-ui/src/taskdog/tui/widgets/vi_navigation_mixin.py:116)
