name: Question
description: Ask a question about using taskdog
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context
      placeholder: I'm trying to...
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already tried?
      placeholder: I looked at the documentation but...
    validations:
      required: false
