"""
Builder classes for constructing test objects.

This module provides builder pattern implementations to simplify test data creation
and improve test readability.
"""

from datetime import datetime

from taskdog_core.domain.entities.task import Task, TaskStatus


class TaskBuilder:
    """Builder for creating test tasks with sensible defaults.

    Uses the Fluent API pattern for readable test setup. Provides sensible defaults
    for all fields, which can be overridden as needed.

    Example:
        # Simple task
        task = TaskBuilder().build()

        # Task with specific attributes
        task = (
            TaskBuilder()
            .with_name("Implement feature X")
            .with_priority(1)
            .with_status(TaskStatus.IN_PROGRESS)
            .with_estimated_duration(8.0)
            .build()
        )

        # Task with dependencies
        task = (
            TaskBuilder()
            .with_name("Integration test")
            .with_depends_on([1, 2, 3])
            .build()
        )

        # Fixed task with schedule
        task = (
            TaskBuilder()
            .with_name("Meeting")
            .with_is_fixed(True)
            .with_planned_dates(
                datetime(2025, 1, 15, 10, 0),
                datetime(2025, 1, 15, 11, 0)
            )
            .build()
        )
    """

    def __init__(self):
        """Initialize builder with default values."""
        self.reset()

    def reset(self):
        """Reset builder to default state.

        Default values:
        - id: None (will be auto-generated by repository)
        - name: "Test Task"
        - priority: 3
        - status: PENDING
        - All dates: None
        - estimated_duration: None
        - is_fixed: False
        - depends_on: []
        - tags: []
        - is_archived: False
        """
        self._id: int | None = None
        self._name: str = "Test Task"
        self._priority: int = 3
        self._status: TaskStatus = TaskStatus.PENDING
        self._planned_start: datetime | None = None
        self._planned_end: datetime | None = None
        self._deadline: datetime | None = None
        self._actual_start: datetime | None = None
        self._actual_end: datetime | None = None
        self._estimated_duration: float | None = None
        self._daily_allocations: dict[str, float] | None = None
        self._is_fixed: bool = False
        self._depends_on: list[int] = []
        self._actual_daily_hours: dict[str, float] | None = None
        self._tags: list[str] = []
        self._is_archived: bool = False

    def with_id(self, task_id: int) -> "TaskBuilder":
        """Set task ID.

        Args:
            task_id: Task ID

        Returns:
            Self for chaining
        """
        self._id = task_id
        return self

    def with_name(self, name: str) -> "TaskBuilder":
        """Set task name.

        Args:
            name: Task name

        Returns:
            Self for chaining
        """
        self._name = name
        return self

    def with_priority(self, priority: int) -> "TaskBuilder":
        """Set task priority.

        Args:
            priority: Priority (higher = more important)

        Returns:
            Self for chaining
        """
        self._priority = priority
        return self

    def with_status(self, status: TaskStatus) -> "TaskBuilder":
        """Set task status.

        Args:
            status: TaskStatus enum value

        Returns:
            Self for chaining
        """
        self._status = status
        return self

    def with_planned_dates(
        self, start: datetime | None, end: datetime | None
    ) -> "TaskBuilder":
        """Set planned start and end dates.

        Args:
            start: Planned start datetime
            end: Planned end datetime

        Returns:
            Self for chaining
        """
        self._planned_start = start
        self._planned_end = end
        return self

    def with_deadline(self, deadline: datetime) -> "TaskBuilder":
        """Set task deadline.

        Args:
            deadline: Deadline datetime

        Returns:
            Self for chaining
        """
        self._deadline = deadline
        return self

    def with_actual_dates(
        self, start: datetime | None, end: datetime | None
    ) -> "TaskBuilder":
        """Set actual start and end dates.

        Args:
            start: Actual start datetime
            end: Actual end datetime

        Returns:
            Self for chaining
        """
        self._actual_start = start
        self._actual_end = end
        return self

    def with_estimated_duration(self, hours: float) -> "TaskBuilder":
        """Set estimated duration.

        Args:
            hours: Estimated hours

        Returns:
            Self for chaining
        """
        self._estimated_duration = hours
        return self

    def with_daily_allocations(self, allocations: dict[str, float]) -> "TaskBuilder":
        """Set daily allocations.

        Args:
            allocations: Dict mapping date strings to allocated hours

        Returns:
            Self for chaining
        """
        self._daily_allocations = allocations
        return self

    def with_is_fixed(self, is_fixed: bool) -> "TaskBuilder":
        """Set whether task schedule is fixed.

        Args:
            is_fixed: True if task should not be rescheduled

        Returns:
            Self for chaining
        """
        self._is_fixed = is_fixed
        return self

    def with_depends_on(self, depends_on: list[int]) -> "TaskBuilder":
        """Set task dependencies.

        Args:
            depends_on: List of task IDs this task depends on

        Returns:
            Self for chaining
        """
        self._depends_on = depends_on
        return self

    def with_actual_daily_hours(self, actual_hours: dict[str, float]) -> "TaskBuilder":
        """Set actual daily hours worked.

        Args:
            actual_hours: Dict mapping date strings to actual hours

        Returns:
            Self for chaining
        """
        self._actual_daily_hours = actual_hours
        return self

    def with_tags(self, tags: list[str]) -> "TaskBuilder":
        """Set task tags.

        Args:
            tags: List of tag strings

        Returns:
            Self for chaining
        """
        self._tags = tags
        return self

    def with_is_archived(self, is_archived: bool) -> "TaskBuilder":
        """Set whether task is archived.

        Args:
            is_archived: True if task is archived

        Returns:
            Self for chaining
        """
        self._is_archived = is_archived
        return self

    def build(self) -> Task:
        """Build and return the Task instance.

        Returns:
            Task: Constructed task with all configured attributes

        Note:
            After calling build(), the builder is reset to default state.
        """
        task = Task(
            id=self._id,
            name=self._name,
            priority=self._priority,
            status=self._status,
            planned_start=self._planned_start,
            planned_end=self._planned_end,
            deadline=self._deadline,
            actual_start=self._actual_start,
            actual_end=self._actual_end,
            estimated_duration=self._estimated_duration,
            daily_allocations=self._daily_allocations,
            is_fixed=self._is_fixed,
            depends_on=self._depends_on,
            actual_daily_hours=self._actual_daily_hours,
            tags=self._tags,
            is_archived=self._is_archived,
        )
        self.reset()
        return task
