completion  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:265)
estimation  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:267)
trends  # unused variable (packages/taskdog-server/src/taskdog_server/api/models/responses.py:270)
_.format_commands  # Click override called via duck-typing (packages/taskdog-ui/src/taskdog/cli_main.py:138)
dep_group  # lazy subcommand loaded via string import path (packages/taskdog-ui/src/taskdog/cli/commands/dep/__init__.py:7)
tag_group  # lazy subcommand loaded via string import path (packages/taskdog-ui/src/taskdog/cli/commands/tag/__init__.py:7)
db_group  # lazy subcommand loaded via string import path (packages/taskdog-ui/src/taskdog/cli/commands/db/__init__.py:7)
audit_group  # lazy subcommand loaded via string import path (packages/taskdog-ui/src/taskdog/cli/commands/audit/__init__.py:7)
_.show_audit_logs  # unused method (packages/taskdog-ui/src/taskdog/tui/app.py:478)
_.run_backup  # palette callback via getattr (packages/taskdog-ui/src/taskdog/tui/app.py)
_.toggle_archive  # palette callback via getattr (packages/taskdog-ui/src/taskdog/tui/app.py)
_.loading  # Textual Widget reactive (packages/taskdog-ui/src/taskdog/tui/app.py)
SelectionProvider  # unused import (packages/taskdog-ui/src/taskdog/tui/context.py:12)
SelectionProvider  # unused class (packages/taskdog-ui/src/taskdog/tui/selection.py:9)
_.handle_bindings_clash  # Textual override called by the framework (packages/taskdog-ui/src/taskdog/tui/app.py)
node  # Textual override signature param (packages/taskdog-ui/src/taskdog/tui/app.py)
activity  # StatisticsPayload / StatisticsResponse field (used by API serialization)
_.margin  # Textual widget styles attribute (PlotextPlot styling)
reschedule  # StatisticsPayload / StatisticsResponse field (used by API serialization)
reschedule_rate  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
rescheduled_task_count  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
total_reschedule_events  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
moved_earlier_count  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
lead_time_breakdown  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
chronic_slippers  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
weekly_reschedule_trend  # RescheduleStatistics DTO field (consumed by UI in a follow-up)
total_slip_days  # ChronicSlipperTask DTO field (consumed by UI in a follow-up)
first_deadline  # ChronicSlipperTask DTO field (consumed by UI in a follow-up)
latest_deadline  # ChronicSlipperTask DTO field (consumed by UI in a follow-up)
